#define EEPROM_SIZE 1102
#define EEPROM_SIZE_CONFIG_PARAMS 99
#define EEPROM_SIZE_SCHEDULING 200
#define EEPROM_SIZE_SCHEDULING_INFRARED_COMMANDS 803

#define EEPROM_CONFIG_PARAMS_INITIAL_ADDR 0
#define EEPROM_SCHEDULING_INITIAL_ADDR 99
#define EEPROM_SCHEDULING_INFRARED_COMMANDS_INITIAL_ADDR 299

#define WI_FI_SSID_LEN 27
#define WI_FI_PASSWORD_LEN 27
#define MQTT_ADDRESS_LEN 27
#define MQTT_PORT_LEN 4
#define MQTT_PORT_CHAR_ARRAY_LEN 5
#define MQTT_PORT_CHAR_ARRAY_FORMAT "%5d"
#define CLASSROOM_ID_LEN 5

#define SCHEDULED_COURSE_LEN 27
#define SCHEDULED_CLASS_LEN 6
#define SCHEDULES_EXECUTION_INFO_LEN 1
#define SCHEDULES_LEN 20

#define SCHEDULE_AIR_CONDITIONER_ON_COMMAND_LEN 199
#define SCHEDULE_AIR_CONDITIONER_OFF_COMMAND_LEN 199
#define SCHEDULE_AIR_CONDITIONER_TEMPERATURE_LEN 4

#define CLASSROOM_INFO_TOPIC "Classroom/Info"
#define CLASSROOM_COURSE_SCHEDULING_SET_TOPIC "Classroom/Course/Scheduling/Set"
#define CLASSROOM_COURSE_SCHEDULING_IR_COMMANDS_TOPIC "Classroom/Course/Scheduling/IRCommands"
#define CLASSROOM_AIR_CONDITIONER_IR_COMMAND_TOPIC "Classroom/AirConditioner/IRCommand"
#define MQTT_ID_PREFIX "NodeMCU:"

#define INFRARED_PIN D2
#define DHT_PIN D3

#define DHT_TYPE DHT22
#define INFRARED_FREQ_KHZ 40

#define AIR_CONDITIONER_REMOTE_COMMAND_MAX_LEN 199
#define MQTT_SEND_MESSAGE_MAX_LEN 266
#define MQTT_RECEIVE_MESSAGE_MAX_LEN 3737
